name: Build and Publish Docker
on:
  release:
    types: [published]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download jar
        run: |
          wget https://github.com/ingvord/axsis-virtual-tango-host/releases/download/${GITHUB_REF/refs\/tags\//}/${GITHUB_REF/refs\/tags\//}.jar
          test -e ${GITHUB_REF/refs\/tags\//}.jar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ingvord/axsis-virtual-tango-host

      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: JAR_FILE=${{ GITHUB_REF/refs\/tags\// }}.jar
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}